development:
  adapter: postgresql
  encoding: unicode
  database: devbud_development
  pool: 5
  username: devbud
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: devbud_test
  pool: 5
  username: devbud
  host: localhost
  port: 5432
