# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdfbbd1c3886f2fda6aad633848ab78397810846044550de9668187804c6db8f21d7ee3552546c9908087ce64032214ced4e14eb843bd916bf7baf4ea12739b7

test:
  secret_key_base: 5e8bb7bd0eb8705a3541920519b97cb16814300b89cb0e59469a0c7d3ffdf36263f1132e224c8083cbec34d8a38de92ccdb81cba9326521773dcee759fd1c04e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
